spring:
  application:
    name: worker
  lifecycle:
    timeout-per-shutdown-phase: 15s

  main:
    web-application-type: none

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://worker-db:5434/spring-worker
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    net.greeta.video: DEBUG
    org.springframework.cloud.kubernetes: TRACE
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

info:
  system: Worker Service

management:
  endpoints:
    web:
      exposure:
        include: bindings, configprops, env, flyway, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# kafka related settings
kafka:
  bootstrapServers: "video-kafka1:29092,video-kafka2:29093"


# minio related settings
minio:
  access-key: minio
  secret-key: minio_password
  url: http://video-minio:8086
  bucket:
    store: video
    stream: stream